### ISSUE TITLE
set对象的问题~

### ISSUE THREAD

**Issue by WoJiaoFuXiaoYun** [linghao518/vue-topo#2]
为什么demo项目中可以JSON.stringify(chart.getItems())转出来的Set对象为数组，而我的项目中Set对象转为了'{}'空对象

**Comment by linghao518** [comment]
Hi Viphehe,
chart.getItems()返回的是Chart类中的list，它是一个普通的Object对象。
首先看下浏览器控制台Top.vue 行:123 可否打印出getItems()返回的对象？

**Comment by linghao518** [comment]
hi viphehe,
您是指item对象下的inputIds吗？我并没有做任何处理，直接把整个对象转成json string的，所以应该是Babel将Map对象转成了Object。

**Comment by WoJiaoFuXiaoYun** [comment]
> hi viphehe，
> 您是指item对象下的inputIds吗？我并没有做任何处理，直接把整个对象转成json string的，所以应该是Babel将Map对象转成Object。

已经找到问题原因了，是core-js影响，非常感谢！
